/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca_v2;

import java.awt.Color;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author vanes
 */
public class frm_agregarUsuario extends javax.swing.JFrame {

    public static LinkedList contenedorUsuarios = new LinkedList();
    public int buscar;
    
    public frm_agregarUsuario() {
        initComponents();
    }
    
    public void validar(){
        
        if(txt_idUsuario.getText().isEmpty()){
            txt_idUsuario.setBackground(new Color(251, 197, 197));
        }else{
              txt_idUsuario.setBackground(new Color(224, 251, 197));
        }
        
        if(txt_nombre.getText().isEmpty()){
         txt_nombre.setBackground(new Color(251, 197, 197));
        }else{
              txt_nombre.setBackground(new Color(224, 251, 197));
        }
        
        if(txt_telefono.getText().isEmpty()){
         txt_telefono.setBackground(new Color(251, 197, 197));
        }else{
          txt_telefono.setBackground(new Color(224, 251, 197));
        }
        
        if(txt_correo.getText().isEmpty()){
         txt_correo.setBackground(new Color(251, 197, 197));
        }else if(!txt_correo.getText().contains("@") || !txt_correo.getText().contains(".")){
            validCorreo.setText("*Correo invalido"); 
        }else{
            validCorreo.setText("");
              txt_correo.setBackground(new Color(224, 251, 197));
        }
        
        
        
        if(txt_direccion.getText().isEmpty()){
         txt_direccion.setBackground(new Color(251, 197, 197));
        }else{
              txt_direccion.setBackground(new Color(224, 251, 197));
        }
  
         if(txt_idUsuario.getText().isEmpty() ||
            txt_nombre.getText().isEmpty()    ||
            txt_telefono.getText().isEmpty()  ||
            txt_correo.getText().isEmpty()    || validCorreo.getText().equals("*Correo invalido") ||
            txt_direccion.getText().isEmpty()){
             
             btn_guardar.setEnabled(false);
         }else{
             btn_guardar.setEnabled(true);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        btn_tabla = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        txt_idUsuario = new javax.swing.JTextField();
        validCorreo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario agregar Usuario");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        jLabel1.setText("Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        btn_menu.setBackground(new java.awt.Color(52, 232, 148));
        btn_menu.setText("Menu");
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menuMouseExited(evt);
            }
        });
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 23, 80, 30));

        jLabel2.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 196, -1, -1));

        jLabel3.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        jLabel3.setText("Telefono");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        jLabel4.setText("Correo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        jLabel5.setText("Direccion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombreKeyReleased(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 200, 30));

        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });
        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 200, 30));

        txt_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_correoKeyReleased(evt);
            }
        });
        jPanel1.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 170, 30));

        txt_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_direccionKeyReleased(evt);
            }
        });
        jPanel1.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 170, 30));

        btn_tabla.setBackground(new java.awt.Color(52, 232, 148));
        btn_tabla.setText("Mostrar datos");
        btn_tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tablaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_tablaMouseExited(evt);
            }
        });
        btn_tabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tablaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 300, 30));

        btn_guardar.setBackground(new java.awt.Color(52, 232, 148));
        btn_guardar.setText("Guardar");
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_guardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_guardarMouseExited(evt);
            }
        });
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 80, 30));

        btn_modificar.setBackground(new java.awt.Color(52, 232, 148));
        btn_modificar.setText("Modificar");
        btn_modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_modificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_modificarMouseExited(evt);
            }
        });
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, 30));

        btn_eliminar.setBackground(new java.awt.Color(52, 232, 148));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseExited(evt);
            }
        });
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, 30));

        txt_idUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idUsuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txt_idUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 70, 30));

        validCorreo.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(validCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 196, 90, 20));

        jLabel7.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregarusr1.png"))); // NOI18N
        jLabel7.setText("Registrar usuario");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 290, 130));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fusr.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // Botono guardar datos
        String id=txt_idUsuario.getText();
        String nombre=txt_nombre.getText();
        int telefono=Integer.parseInt(txt_telefono.getText());
        String correo=txt_correo.getText();
        String direccion=txt_direccion.getText();
       
        
        class_usuario usuario=new class_usuario(id, nombre, telefono, correo, direccion);
        contenedorUsuarios.add(usuario);
        
        JOptionPane.showMessageDialog(null, "Datos de usuario registrado");
        
        txt_idUsuario.setText("");
        txt_nombre.setText("");
        txt_telefono.setText("");
        txt_correo.setText("");
        txt_direccion.setText("");
     
        
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txt_idUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idUsuarioKeyTyped
        // Busca los datos
       int press=evt.getKeyChar();
        if(press==10){
            String idEncontrado=txt_idUsuario.getText().trim();
            class_usuario usuario;
            for(int i = 0; i < contenedorUsuarios.size(); i++){
                usuario=(class_usuario)contenedorUsuarios.get(i);
                if(idEncontrado.equalsIgnoreCase(usuario.getId_Usuario())){
                    txt_nombre.setText(usuario.getNombre());
                    txt_telefono.setText(Integer.toString(usuario.getTelefono()));
                    txt_correo.setText(usuario.getCorreo());
                    txt_direccion.setText(usuario.getDireccion()); 
                    buscar=i;
                    break;
                    
                }//Fin if
                    
            }//fin for
            
        }//Fin if
    }//GEN-LAST:event_txt_idUsuarioKeyTyped

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // Boton modificar
        String id=txt_idUsuario.getText();
        String nombre=txt_nombre.getText();
        int telefono=Integer.parseInt(txt_telefono.getText());
        String correo=txt_correo.getText();
        String direccion=txt_direccion.getText();
       
        
        class_usuario usuario=new class_usuario(id, nombre, telefono, correo, direccion);
        contenedorUsuarios.set(buscar, usuario);
        
        JOptionPane.showMessageDialog(null, "Datos de usuario modificado");
        
        txt_idUsuario.setText("");
        txt_nombre.setText("");
        txt_telefono.setText("");
        txt_correo.setText("");
        txt_direccion.setText("");
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // Boton eliminar
         contenedorUsuarios.remove(buscar);
        txt_idUsuario.setText("");
        txt_nombre.setText("");
        txt_telefono.setText("");
        txt_correo.setText("");
        txt_direccion.setText("");
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // Boton menu
        Menu abrir=new Menu();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_tablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tablaActionPerformed
        // Boton tabla datos
        csl_usuario abrir=new csl_usuario();
        abrir.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_tablaActionPerformed

    private void txt_idUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idUsuarioKeyReleased
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_txt_idUsuarioKeyReleased

    private void txt_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyReleased
        // TODO add your handling code here:
         validar();
    }//GEN-LAST:event_txt_nombreKeyReleased

    private void txt_telefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyReleased
        // TODO add your handling code here:
         validar();
    }//GEN-LAST:event_txt_telefonoKeyReleased

    private void txt_correoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_correoKeyReleased
        // TODO add your handling code here:
         validar();
    }//GEN-LAST:event_txt_correoKeyReleased

    private void txt_direccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionKeyReleased
        // TODO add your handling code here:
         validar();
    }//GEN-LAST:event_txt_direccionKeyReleased

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        
        if(Character.isLetter((validar))){
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void btn_guardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseEntered
        // TODO add your handling code here:
        btn_guardar.setBackground(new Color(52, 232, 148));
    }//GEN-LAST:event_btn_guardarMouseEntered

    private void btn_guardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseExited
        // TODO add your handling code here:
        btn_guardar.setBackground(new Color(52, 226, 232));
    }//GEN-LAST:event_btn_guardarMouseExited

    private void btn_modificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseEntered
        // TODO add your handling code here:
        btn_modificar.setBackground(new Color(52, 232, 148));
    }//GEN-LAST:event_btn_modificarMouseEntered

    private void btn_modificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificarMouseExited
        // TODO add your handling code here:
         btn_modificar.setBackground(new Color(52, 226, 232));
    }//GEN-LAST:event_btn_modificarMouseExited

    private void btn_eliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseEntered
        // TODO add your handling code here:
        btn_eliminar.setBackground(new Color(52, 232, 148));
    }//GEN-LAST:event_btn_eliminarMouseEntered

    private void btn_eliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseExited
        // TODO add your handling code here:
        btn_eliminar.setBackground(new Color(52, 226, 232));
    }//GEN-LAST:event_btn_eliminarMouseExited

    private void btn_tablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tablaMouseEntered
        // TODO add your handling code here:
         btn_tabla.setBackground(new Color(52, 232, 148));
    }//GEN-LAST:event_btn_tablaMouseEntered

    private void btn_tablaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tablaMouseExited
        // TODO add your handling code here:
        btn_tabla.setBackground(new Color(52, 226, 232));
    }//GEN-LAST:event_btn_tablaMouseExited

    private void btn_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseEntered
        // TODO add your handling code here:
        btn_menu.setBackground(new Color(52, 232, 148));
    }//GEN-LAST:event_btn_menuMouseEntered

    private void btn_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseExited
        // TODO add your handling code here:
        btn_menu.setBackground(new Color(52, 226, 232));
    }//GEN-LAST:event_btn_menuMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_agregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_agregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_agregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_agregarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_agregarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_idUsuario;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JLabel validCorreo;
    // End of variables declaration//GEN-END:variables
}
